git.py: Add tagger to annotated tag
`git hash-object` 2.40+ fails without a tagger entry.

	error: object fails fsck: missingTaggerEntry: invalid format - expected 'tagger' line
	fatal: refusing to create malformed object

Only ancient versions of git created tag objects without tagger
information.

As the `ref` does not currently contain tagger information, this uses a
placeholder value that matches `git fast-export --fake-missing-tagger`.